[build]
  base = "/"
  publish = "dist"
  command = "npm run generate"

# Redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Handle trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true